import { readFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';
import type { Page } from '@playwright/test';

async function confirmDemo(page: Page) {
  await page.getByRole('navigation').getByRole('link', { name: 'Escanear', exact: true }).click();
  await page.getByRole('button', { name: 'Simular captura' }).click();
  await page.getByRole('radio', { name: /Gorrión común/ }).check();
  await page.getByLabel('Municipio del encuentro').selectOption('algete');
  await page.getByLabel('Contexto', { exact: true }).selectOption('wild');
  await page.getByLabel('Entorno declarado').selectOption('garden');
  await page.getByRole('button', { name: 'Confirmar y guardar' }).dblclick();
}

test('descubrimiento, repetición, filtros, edición y borrado con IndexedDB real', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Tu nombre (opcional)').fill('Explorador');
  await page.getByRole('link', { name: 'Probar demostración', exact: true }).click();
  await expect(page.getByText('Demostración: resultados simulados')).toBeVisible();
  await confirmDemo(page);
  await expect(page.getByRole('heading', { name: 'Un nuevo descubrimiento' })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('revelacion.png'), fullPage: true });
  await page.getByRole('link', { name: 'Ver ficha e historial' }).click();
  await expect(page.getByRole('heading', { name: 'Mis encuentros · 1' })).toBeVisible();
  await confirmDemo(page);
  await expect(page.getByRole('heading', { name: 'Otro encuentro, otra historia' })).toBeVisible();
  await page.reload();
  await page.getByRole('navigation').getByRole('link', { name: 'Colección', exact: true }).click();
  await expect(page.getByText('1 descubiertas de 8 fichas de ejemplo.')).toBeVisible();
  await page.getByLabel('Buscar especie').fill('nada-coincide');
  await expect(page.getByRole('heading', { name: 'Ninguna ficha coincide' })).toBeVisible();
  await page.getByRole('button', { name: 'Limpiar filtros' }).click();
  await page.getByLabel('Grupo', { exact: true }).selectOption('birds');
  await page.getByLabel('Estado', { exact: true }).selectOption('discovered');
  await page.getByRole('link', { name: /Gorrión común/ }).click();
  await page.getByRole('button', { name: '← Volver', exact: true }).click();
  await expect(page.getByLabel('Grupo', { exact: true })).toHaveValue('birds');
  await expect(page.getByLabel('Estado', { exact: true })).toHaveValue('discovered');
  await page.getByRole('navigation').getByRole('link', { name: 'Cuaderno', exact: true }).click();
  await expect(page.getByText('2 encuentros guardados en este perfil local.')).toBeVisible();
  await page.getByRole('link', { name: /Gorrión común/ }).first().click();
  await page.getByRole('button', { name: 'Editar encuentro', exact: true }).click();
  await page.getByLabel('Especie', { exact: true }).selectOption('demo-mirlo');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(page.getByRole('button', { name: 'Guardar cambios' })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Mirlo común', exact: true })).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: 'Colección', exact: true }).click();
  await expect(page.getByText('2 descubiertas de 8 fichas de ejemplo.')).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: 'Cuaderno', exact: true }).click();
  await page.getByRole('link', { name: /Mirlo común/ }).click();
  await page.getByRole('button', { name: 'Eliminar encuentro', exact: true }).click();
  await page.getByRole('button', { name: 'Sí, eliminar encuentro' }).click();
  await expect(page.getByText('1 encuentros guardados en este perfil local.')).toBeVisible();
  await page.reload();
  await page.getByRole('navigation').getByRole('link', { name: 'Colección', exact: true }).click();
  await expect(page.getByText('1 descubiertas de 8 fichas de ejemplo.')).toBeVisible();
});

test('foto, copia/restauración, archivo inválido y frontera real/demo', async ({ page }) => {
  await page.goto('/demo/escanear');
  const png = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 64; canvas.height = 64; const context = canvas.getContext('2d')!; context.fillStyle = '#116c69'; context.fillRect(0, 0, 64, 64); return canvas.toDataURL('image/png').split(',')[1]!; });
  await page.getByLabel('Elegir foto local (opcional)').setInputFiles({ name: 'fixture-sintetico.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') });
  await expect(page.getByText(/Copia preparada:/)).toBeVisible();
  await page.getByLabel('Notas (opcional)').fill('Fixture de prueba, sin dato personal');
  await page.getByRole('button', { name: 'Guardar pendiente', exact: true }).click();
  await expect(page.getByRole('img', { name: 'Foto de tu encuentro' })).toBeVisible();
  await page.getByRole('link', { name: 'Ajustes', exact: true }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exportar copia', exact: true }).click();
  const download = await downloadPromise;
  const buffer = await readFile((await download.path())!);
  const previousProfile = await page.getByLabel('Perfil activo').inputValue();
  await page.getByLabel('Restaurar copia JSON').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer });
  await expect(page.getByRole('status')).toHaveText('Copia restaurada en un perfil nuevo.');
  await expect(page.getByLabel('Perfil activo')).not.toHaveValue(previousProfile);
  const restoredProfile = await page.getByLabel('Perfil activo').inputValue();
  await page.getByLabel('Restaurar copia JSON').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":999}') });
  await expect(page.getByRole('alert')).toContainText('incompatible');
  await expect(page.getByLabel('Perfil activo')).toHaveValue(restoredProfile);
  await page.getByRole('navigation').getByRole('link', { name: 'Cuaderno', exact: true }).click();
  await page.getByRole('link', { name: /Encuentro pendiente/ }).click();
  await expect(page.getByRole('img', { name: 'Foto de tu encuentro' })).toBeVisible();
  await expect(page.getByText('Fixture de prueba, sin dato personal')).toBeVisible();
  await page.getByRole('button', { name: 'Editar encuentro', exact: true }).click();
  await page.getByLabel('Especie', { exact: true }).selectOption('demo-mirlo');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(page.getByRole('button', { name: 'Guardar cambios' })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Mirlo común', exact: true })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Foto de tu encuentro' })).toBeVisible();
  await page.goto('/real/cuaderno');
  await expect(page.getByText('0 encuentros guardados en este perfil local.')).toBeVisible();
  await page.getByRole('link', { name: 'Ajustes', exact: true }).click();
  await page.getByLabel('Restaurar copia JSON').setInputFiles({ name: 'demo.json', mimeType: 'application/json', buffer });
  await expect(page.getByRole('alert')).toContainText('otro espacio');
  await page.getByRole('navigation').getByRole('link', { name: 'Escanear', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Simular captura' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Confirmar y guardar' })).toHaveCount(0);
  await page.getByLabel('Notas (opcional)').fill('Pendiente exclusivo real');
  await page.getByRole('button', { name: 'Guardar pendiente', exact: true }).click();
  await expect(page.getByText('Pendiente exclusivo real')).toBeVisible();
  await page.reload();
  await expect(page.getByText('Pendiente exclusivo real')).toBeVisible();
  await page.goto('/demo/cuaderno');
  await expect(page.getByRole('link', { name: /Mirlo común/ })).toBeVisible();
  await expect(page.getByText('Pendiente exclusivo real')).toHaveCount(0);
});

test('corregir contexto, municipio y pendiente recalcula las colecciones tras recarga', async ({ page }) => {
  await page.goto('/demo');
  await confirmDemo(page);
  await page.getByRole('button', { name: 'Continuar sin revelación' }).click();
  const encounterUrl = page.url();
  await page.goto('/demo/colecciones/algete');
  await expect(page.getByText('1 / 7 especies que cumplen la regla')).toBeVisible();
  await page.goto(encounterUrl);
  await page.getByRole('button', { name: 'Editar encuentro', exact: true }).click();
  await page.getByLabel('Contexto', { exact: true }).selectOption('domestic');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(page.getByRole('button', { name: 'Guardar cambios' })).toHaveCount(0);
  await page.goto('/demo/colecciones/algete');
  await expect(page.getByText('0 / 7 especies que cumplen la regla')).toBeVisible();
  await page.goto(encounterUrl);
  await page.getByRole('button', { name: 'Editar encuentro', exact: true }).click();
  await page.getByLabel('Contexto', { exact: true }).selectOption('wild');
  await page.getByLabel('Municipio del encuentro').selectOption('san-agustin');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(page.getByRole('button', { name: 'Guardar cambios' })).toHaveCount(0);
  await page.goto('/demo/colecciones/san-agustin');
  await expect(page.getByText('1 / 7 especies que cumplen la regla')).toBeVisible();
  await page.goto('/demo/colecciones/algete');
  await expect(page.getByText('0 / 7 especies que cumplen la regla')).toBeVisible();
  await page.goto(encounterUrl);
  await page.getByRole('button', { name: 'Editar encuentro', exact: true }).click();
  await page.getByLabel('Especie', { exact: true }).selectOption('');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(page.getByRole('button', { name: 'Guardar cambios' })).toHaveCount(0);
  await page.goto('/demo/coleccion');
  await expect(page.getByText('0 descubiertas de 8 fichas de ejemplo.')).toBeVisible();
  await page.goto('/demo/colecciones/san-agustin');
  await expect(page.getByText('0 / 7 especies que cumplen la regla')).toBeVisible();
});

test('retorno local directo y navegación conservan filtros de municipio, lista y cuaderno', async ({ page }) => {
  await page.goto('/');
  await page.goto('/demo/ficha/demo-gorrion');
  await page.getByRole('button', { name: '← Volver', exact: true }).click();
  await expect(page).toHaveURL(/\/demo\/coleccion$/);
  await page.goto('/demo/colecciones/algete');
  await page.getByRole('button', { name: '← Volver', exact: true }).click();
  await expect(page).toHaveURL(/\/demo$/);
  await page.getByLabel('Municipio para explorar').selectOption('algete');
  await page.getByRole('link', { name: /Vecinos de Algete/ }).click();
  await page.getByLabel('Grupo', { exact: true }).selectOption('birds');
  await page.getByRole('link', { name: /Gorrión común/ }).click();
  await page.getByRole('button', { name: '← Volver', exact: true }).click();
  await expect(page).toHaveURL(/\/colecciones\/algete\?grupo=birds$/);
  await expect(page.getByLabel('Grupo', { exact: true })).toHaveValue('birds');
  await page.getByRole('button', { name: '← Volver', exact: true }).click();
  await expect(page.getByLabel('Municipio para explorar')).toHaveValue('algete');
  await page.goto('/demo/escanear');
  await page.getByRole('button', { name: 'Guardar pendiente', exact: true }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Cuaderno', exact: true }).click();
  await page.getByLabel('Estado del encuentro').selectOption('pending');
  await page.getByRole('link', { name: /Encuentro pendiente/ }).click();
  await page.getByRole('button', { name: '← Cuaderno', exact: true }).click();
  await expect(page.getByLabel('Estado del encuentro')).toHaveValue('pending');
});

test('fallo demo conserva borrador y reintento no duplica; pantalla estrecha', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 });
  await page.goto('/demo/ajustes');
  await page.getByText('Panel local de escenarios', { exact: true }).click();
  await page.getByLabel('Escenario demo').selectOption('storage');
  await page.getByRole('link', { name: 'Abrir captura del escenario' }).click();
  await page.getByLabel('Notas (opcional)').fill('Borrador conservado');
  await page.getByRole('button', { name: 'Guardar pendiente' }).click();
  await expect(page.getByRole('alert')).toContainText('El borrador se conserva');
  await expect(page.getByLabel('Notas (opcional)')).toHaveValue('Borrador conservado');
  await page.getByRole('button', { name: 'Guardar pendiente' }).click();
  await expect(page.getByText('Borrador conservado')).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: 'Cuaderno', exact: true }).click();
  await expect(page.getByText('1 encuentros guardados en este perfil local.')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('cuaderno-320.png'), fullPage: true });
});
